In [67]:
from ID3 import ID3DecisionTreeClassifier
from sklearn import datasets, svm, metrics
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

## scikit-learn Decision Tree

In [3]:
data, target = datasets.load_digits(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3)

clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

y_hat = clf.predict(X_test)

print(classification_report(y_test, y_hat))
print(confusion_matrix(y_test, y_hat))

id3 = ID3DecisionTreeClassifier()

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        51
           1       0.86      0.91      0.89        56
           2       0.95      0.76      0.85        54
           3       0.75      0.78      0.76        50
           4       0.80      0.86      0.83        50
           5       0.92      0.87      0.89        62
           6       0.93      0.89      0.91        57
           7       0.75      0.88      0.81        48
           8       0.83      0.81      0.82        53
           9       0.84      0.81      0.83        59

    accuracy                           0.86       540
   macro avg       0.86      0.86      0.85       540
weighted avg       0.86      0.86      0.86       540

[[50  0  0  0  1  0  0  0  0  0]
 [ 0 51  0  0  3  0  0  1  0  1]
 [ 0  1 41  4  0  0  2  3  2  1]
 [ 0  2  0 39  0  1  0  4  2  2]
 [ 0  1  0  0 43  0  1  2  1  2]
 [ 0  1  0  1  2 54  1  0  1  2]
 [ 0  1  0  1  4  0 51  0  0  0]
 [ 0  1  0

## Own Decision Tree

In [68]:
X_train.shape

(1257, 64)

In [73]:
from collections import defaultdict

attributes = {}

for pxl in range(64): 
    attributes[str(pxl)] = np.array(range(17))
    
attributes

{'0': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '1': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '2': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '3': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '4': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '5': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '6': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '7': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '8': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '9': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '10': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '11': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 '

In [70]:
id3_clf = ID3DecisionTreeClassifier()

tree = id3_clf.fit(X_train, y_train, attributes, None)


id: 4
label: 4
entropy: 0
samples: 2
classCounts: Counter({4: 2})
value: 0
3 -> 4

id: 5
label: 4
entropy: 0
samples: 4
classCounts: Counter({4: 4})
value: 1
3 -> 5

id: 6
label: 4
entropy: 0
samples: 7
classCounts: Counter({4: 7})
value: 2
3 -> 6

id: 7
label: 4
entropy: 0
samples: 2
classCounts: Counter({4: 2})
value: 3
3 -> 7

id: 9
label: 4
samples: 0
classCount: Counter()
8 -> 9

id: 10
label: 4
samples: 0
classCount: Counter()
8 -> 10

id: 11
label: 4
samples: 0
classCount: Counter()
8 -> 11

id: 12
label: 4
samples: 0
classCount: Counter()
8 -> 12

id: 13
label: 4
samples: 0
classCount: Counter()
8 -> 13

id: 14
label: 4
samples: 0
classCount: Counter()
8 -> 14

id: 15
label: 4
samples: 0
classCount: Counter()
8 -> 15

id: 16
label: 4
samples: 0
classCount: Counter()
8 -> 16

id: 17
label: 4
samples: 0
classCount: Counter()
8 -> 17

id: 18
label: 4
samples: 0
classCount: Counter()
8 -> 18

id: 19
label: 4
samples: 0
classCount: Counter()
8 -> 19

id: 20
label: 7
entropy: 0
samp

123 -> 124

id: 126
label: 5
samples: 0
classCount: Counter()
125 -> 126

id: 127
label: 5
samples: 0
classCount: Counter()
125 -> 127

id: 128
label: 5
samples: 0
classCount: Counter()
125 -> 128

id: 129
label: 5
samples: 0
classCount: Counter()
125 -> 129

id: 130
label: 5
samples: 0
classCount: Counter()
125 -> 130

id: 131
label: 5
samples: 0
classCount: Counter()
125 -> 131

id: 132
label: 5
samples: 0
classCount: Counter()
125 -> 132

id: 133
label: 5
samples: 0
classCount: Counter()
125 -> 133

id: 134
label: 5
samples: 0
classCount: Counter()
125 -> 134

id: 135
label: 5
entropy: 0
samples: 1
classCounts: Counter({5: 1})
value: 9
125 -> 135

id: 136
label: 5
samples: 0
classCount: Counter()
125 -> 136

id: 137
label: 5
entropy: 0
samples: 1
classCounts: Counter({5: 1})
value: 11
125 -> 137

id: 138
label: 5
samples: 0
classCount: Counter()
125 -> 138

id: 139
label: 2
entropy: 0
samples: 1
classCounts: Counter({2: 1})
value: 13
125 -> 139

id: 140
label: 5
samples: 0
classCoun

280 -> 281

id: 282
label: 5
samples: 0
classCount: Counter()
280 -> 282

id: 283
label: 5
samples: 0
classCount: Counter()
280 -> 283

id: 284
label: 6
entropy: 0
samples: 1
classCounts: Counter({6: 1})
value: 3
280 -> 284

id: 285
label: 5
entropy: 0
samples: 1
classCounts: Counter({5: 1})
value: 4
280 -> 285

id: 286
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 5
280 -> 286

id: 287
label: 5
entropy: 0
samples: 1
classCounts: Counter({5: 1})
value: 6
280 -> 287

id: 288
label: 5
samples: 0
classCount: Counter()
280 -> 288

id: 289
label: 5
samples: 0
classCount: Counter()
280 -> 289

id: 290
label: 5
entropy: 0
samples: 2
classCounts: Counter({5: 2})
value: 9
280 -> 290

id: 291
label: 5
samples: 0
classCount: Counter()
280 -> 291

id: 292
label: 6
entropy: 0
samples: 1
classCounts: Counter({6: 1})
value: 11
280 -> 292

id: 293
label: 5
samples: 0
classCount: Counter()
280 -> 293

id: 294
label: 5
samples: 0
classCount: Counter()
280 -> 294

id: 295
label: 3
en

405 -> 406

id: 407
label: 5
entropy: 0
samples: 1
classCounts: Counter({5: 1})
value: 1
405 -> 407

id: 409
label: 1
samples: 0
classCount: Counter()
408 -> 409

id: 410
label: 1
samples: 0
classCount: Counter()
408 -> 410

id: 411
label: 1
samples: 0
classCount: Counter()
408 -> 411

id: 412
label: 1
samples: 0
classCount: Counter()
408 -> 412

id: 413
label: 1
samples: 0
classCount: Counter()
408 -> 413

id: 414
label: 1
samples: 0
classCount: Counter()
408 -> 414

id: 415
label: 1
samples: 0
classCount: Counter()
408 -> 415

id: 416
label: 1
samples: 0
classCount: Counter()
408 -> 416

id: 417
label: 1
samples: 0
classCount: Counter()
408 -> 417

id: 418
label: 1
samples: 0
classCount: Counter()
408 -> 418

id: 419
label: 1
samples: 0
classCount: Counter()
408 -> 419

id: 420
label: 1
samples: 0
classCount: Counter()
408 -> 420

id: 421
label: 1
samples: 0
classCount: Counter()
408 -> 421

id: 422
label: 2
entropy: 0
samples: 1
classCounts: Counter({2: 1})
value: 13
408 -> 422

id:

530 -> 531

id: 532
label: 4
samples: 0
classCount: Counter()
530 -> 532

id: 533
label: 4
samples: 0
classCount: Counter()
530 -> 533

id: 534
label: 1
entropy: 0
samples: 2
classCounts: Counter({1: 2})
value: 3
530 -> 534

id: 535
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 4
530 -> 535

id: 536
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 5
530 -> 536

id: 537
label: 4
samples: 0
classCount: Counter()
530 -> 537

id: 538
label: 4
samples: 0
classCount: Counter()
530 -> 538

id: 539
label: 4
samples: 0
classCount: Counter()
530 -> 539

id: 540
label: 4
samples: 0
classCount: Counter()
530 -> 540

id: 541
label: 4
samples: 0
classCount: Counter()
530 -> 541

id: 542
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 11
530 -> 542

id: 543
label: 4
samples: 0
classCount: Counter()
530 -> 543

id: 544
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 13
530 -> 544

id: 545
label: 4
samples: 0
classCount: Count

679 -> 680

id: 681
label: 2
samples: 0
classCount: Counter()
679 -> 681

id: 682
label: 2
samples: 0
classCount: Counter()
679 -> 682

id: 683
label: 2
samples: 0
classCount: Counter()
679 -> 683

id: 684
label: 2
samples: 0
classCount: Counter()
679 -> 684

id: 685
label: 2
samples: 0
classCount: Counter()
679 -> 685

id: 686
label: 2
samples: 0
classCount: Counter()
679 -> 686

id: 687
label: 2
samples: 0
classCount: Counter()
679 -> 687

id: 688
label: 2
samples: 0
classCount: Counter()
679 -> 688

id: 689
label: 2
samples: 0
classCount: Counter()
679 -> 689

id: 690
label: 2
samples: 0
classCount: Counter()
679 -> 690

id: 691
label: 2
samples: 0
classCount: Counter()
679 -> 691

id: 692
label: 5
entropy: 0
samples: 1
classCounts: Counter({5: 1})
value: 12
679 -> 692

id: 693
label: 5
entropy: 0
samples: 1
classCounts: Counter({5: 1})
value: 13
679 -> 693

id: 694
label: 2
samples: 0
classCount: Counter()
679 -> 694

id: 695
label: 2
entropy: 0
samples: 1
classCounts: Counter({2: 

805 -> 806

id: 807
label: 4
entropy: 0
samples: 2
classCounts: Counter({4: 2})
value: 1
805 -> 807

id: 808
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 2
805 -> 808

id: 809
label: 4
samples: 0
classCount: Counter()
805 -> 809

id: 810
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 4
805 -> 810

id: 811
label: 1
entropy: 0
samples: 3
classCounts: Counter({1: 3})
value: 5
805 -> 811

id: 812
label: 4
samples: 0
classCount: Counter()
805 -> 812

id: 813
label: 7
entropy: 0
samples: 1
classCounts: Counter({7: 1})
value: 7
805 -> 813

id: 814
label: 4
samples: 0
classCount: Counter()
805 -> 814

id: 815
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 9
805 -> 815

id: 816
label: 4
samples: 0
classCount: Counter()
805 -> 816

id: 817
label: 4
entropy: 0
samples: 2
classCounts: Counter({4: 2})
value: 11
805 -> 817

id: 818
label: 4
samples: 0
classCount: Counter()
805 -> 818

id: 819
label: 4
samples: 0
classCount: Counter()
805 

975 -> 976

id: 977
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 1
975 -> 977

id: 978
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 2
975 -> 978

id: 979
label: 1
samples: 0
classCount: Counter()
975 -> 979

id: 980
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 4
975 -> 980

id: 981
label: 6
entropy: 0
samples: 1
classCounts: Counter({6: 1})
value: 5
975 -> 981

id: 983
label: 1
samples: 0
classCount: Counter()
982 -> 983

id: 984
label: 1
entropy: 0
samples: 1
classCounts: Counter({1: 1})
value: 1
982 -> 984

id: 985
label: 1
samples: 0
classCount: Counter()
982 -> 985

id: 986
label: 1
entropy: 0
samples: 1
classCounts: Counter({1: 1})
value: 3
982 -> 986

id: 987
label: 1
samples: 0
classCount: Counter()
982 -> 987

id: 988
label: 1
samples: 0
classCount: Counter()
982 -> 988

id: 989
label: 1
samples: 0
classCount: Counter()
982 -> 989

id: 990
label: 1
samples: 0
classCount: Counter()
982 -> 990

id: 991
label: 7
ent

1153 -> 1154

id: 1155
label: 7
samples: 0
classCount: Counter()
1153 -> 1155

id: 1156
label: 7
samples: 0
classCount: Counter()
1153 -> 1156

id: 1157
label: 7
samples: 0
classCount: Counter()
1153 -> 1157

id: 1158
label: 7
samples: 0
classCount: Counter()
1153 -> 1158

id: 1159
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 5
1153 -> 1159

id: 1160
label: 7
samples: 0
classCount: Counter()
1153 -> 1160

id: 1161
label: 7
samples: 0
classCount: Counter()
1153 -> 1161

id: 1162
label: 7
entropy: 0
samples: 1
classCounts: Counter({7: 1})
value: 8
1153 -> 1162

id: 1163
label: 7
samples: 0
classCount: Counter()
1153 -> 1163

id: 1164
label: 7
samples: 0
classCount: Counter()
1153 -> 1164

id: 1165
label: 7
samples: 0
classCount: Counter()
1153 -> 1165

id: 1166
label: 7
samples: 0
classCount: Counter()
1153 -> 1166

id: 1167
label: 7
samples: 0
classCount: Counter()
1153 -> 1167

id: 1168
label: 7
samples: 0
classCount: Counter()
1153 -> 1168

id: 1169
label: 7
samp

1336 -> 1337

id: 1338
label: 2
samples: 0
classCount: Counter()
1336 -> 1338

id: 1339
label: 2
samples: 0
classCount: Counter()
1336 -> 1339

id: 1340
label: 2
samples: 0
classCount: Counter()
1336 -> 1340

id: 1341
label: 2
samples: 0
classCount: Counter()
1336 -> 1341

id: 1342
label: 2
samples: 0
classCount: Counter()
1336 -> 1342

id: 1343
label: 2
samples: 0
classCount: Counter()
1336 -> 1343

id: 1344
label: 2
samples: 0
classCount: Counter()
1336 -> 1344

id: 1345
label: 2
samples: 0
classCount: Counter()
1336 -> 1345

id: 1346
label: 2
samples: 0
classCount: Counter()
1336 -> 1346

id: 1347
label: 2
samples: 0
classCount: Counter()
1336 -> 1347

id: 1348
label: 2
samples: 0
classCount: Counter()
1336 -> 1348

id: 1349
label: 3
entropy: 0
samples: 2
classCounts: Counter({3: 2})
value: 12
1336 -> 1349

id: 1350
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 13
1336 -> 1350

id: 1351
label: 2
entropy: 0
samples: 1
classCounts: Counter({2: 1})
value: 14
1336 -

1486 -> 1487

id: 1488
label: 0
samples: 0
classCount: Counter()
1486 -> 1488

id: 1489
label: 0
samples: 0
classCount: Counter()
1486 -> 1489

id: 1490
label: 4
entropy: 0
samples: 1
classCounts: Counter({4: 1})
value: 3
1486 -> 1490

id: 1491
label: 0
samples: 0
classCount: Counter()
1486 -> 1491

id: 1492
label: 0
samples: 0
classCount: Counter()
1486 -> 1492

id: 1493
label: 0
samples: 0
classCount: Counter()
1486 -> 1493

id: 1494
label: 0
samples: 0
classCount: Counter()
1486 -> 1494

id: 1495
label: 0
samples: 0
classCount: Counter()
1486 -> 1495

id: 1496
label: 0
samples: 0
classCount: Counter()
1486 -> 1496

id: 1497
label: 0
samples: 0
classCount: Counter()
1486 -> 1497

id: 1498
label: 0
samples: 0
classCount: Counter()
1486 -> 1498

id: 1499
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 12
1486 -> 1499

id: 1500
label: 0
samples: 0
classCount: Counter()
1486 -> 1500

id: 1501
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 14
1486 ->

1618 -> 1619

id: 1620
label: 3
samples: 0
classCount: Counter()
1618 -> 1620

id: 1621
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 2
1618 -> 1621

id: 1622
label: 3
samples: 0
classCount: Counter()
1618 -> 1622

id: 1623
label: 3
samples: 0
classCount: Counter()
1618 -> 1623

id: 1624
label: 3
samples: 0
classCount: Counter()
1618 -> 1624

id: 1625
label: 3
samples: 0
classCount: Counter()
1618 -> 1625

id: 1626
label: 3
samples: 0
classCount: Counter()
1618 -> 1626

id: 1627
label: 3
samples: 0
classCount: Counter()
1618 -> 1627

id: 1628
label: 3
samples: 0
classCount: Counter()
1618 -> 1628

id: 1629
label: 3
samples: 0
classCount: Counter()
1618 -> 1629

id: 1630
label: 3
samples: 0
classCount: Counter()
1618 -> 1630

id: 1631
label: 3
samples: 0
classCount: Counter()
1618 -> 1631

id: 1632
label: 3
samples: 0
classCount: Counter()
1618 -> 1632

id: 1633
label: 3
samples: 0
classCount: Counter()
1618 -> 1633

id: 1634
label: 3
samples: 0
classCount: Counter(

1729 -> 1742

id: 1743
label: 0
samples: 0
classCount: Counter()
1729 -> 1743

id: 1744
label: 0
samples: 0
classCount: Counter()
1729 -> 1744

id: 1745
label: 0
samples: 0
classCount: Counter()
1729 -> 1745

id: 1746
label: 0
samples: 0
classCount: Counter()
1729 -> 1746

id: 1729
attribute: 1
entropy: 0.5032583347756457
samples: 9
classCounts: Counter({0: 8, 9: 1})
value: 0
1728 -> 1729

id: 1747
label: 8
samples: 0
classCount: Counter()
1728 -> 1747

id: 1748
label: 8
samples: 0
classCount: Counter()
1728 -> 1748

id: 1749
label: 8
samples: 0
classCount: Counter()
1728 -> 1749

id: 1750
label: 8
samples: 0
classCount: Counter()
1728 -> 1750

id: 1751
label: 8
samples: 0
classCount: Counter()
1728 -> 1751

id: 1752
label: 8
entropy: 0
samples: 2
classCounts: Counter({8: 2})
value: 6
1728 -> 1752

id: 1754
label: 3
samples: 0
classCount: Counter()
1753 -> 1754

id: 1755
label: 3
samples: 0
classCount: Counter()
1753 -> 1755

id: 1756
label: 3
samples: 0
classCount: Counter()
1753 -> 1


id: 1884
label: 0
entropy: 0
samples: 3
classCounts: Counter({0: 3})
value: 0
1883 -> 1884

id: 1885
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 1
1883 -> 1885

id: 1886
label: 9
samples: 0
classCount: Counter()
1883 -> 1886

id: 1887
label: 9
samples: 0
classCount: Counter()
1883 -> 1887

id: 1888
label: 9
samples: 0
classCount: Counter()
1883 -> 1888

id: 1889
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 5
1883 -> 1889

id: 1890
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 6
1883 -> 1890

id: 1891
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 7
1883 -> 1891

id: 1892
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 8
1883 -> 1892

id: 1893
label: 9
samples: 0
classCount: Counter()
1883 -> 1893

id: 1894
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 10
1883 -> 1894

id: 1895
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 11
1883 -> 1895

i


id: 2021
label: 0
entropy: 0
samples: 2
classCounts: Counter({0: 2})
value: 0
2020 -> 2021

id: 2022
label: 0
entropy: 0
samples: 2
classCounts: Counter({0: 2})
value: 1
2020 -> 2022

id: 2023
label: 0
samples: 0
classCount: Counter()
2020 -> 2023

id: 2024
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 3
2020 -> 2024

id: 2025
label: 8
entropy: 0
samples: 2
classCounts: Counter({8: 2})
value: 4
2020 -> 2025

id: 2026
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 5
2020 -> 2026

id: 2027
label: 0
entropy: 0
samples: 2
classCounts: Counter({0: 2})
value: 6
2020 -> 2027

id: 2028
label: 0
samples: 0
classCount: Counter()
2020 -> 2028

id: 2029
label: 0
samples: 0
classCount: Counter()
2020 -> 2029

id: 2030
label: 0
samples: 0
classCount: Counter()
2020 -> 2030

id: 2031
label: 0
samples: 0
classCount: Counter()
2020 -> 2031

id: 2032
label: 0
samples: 0
classCount: Counter()
2020 -> 2032

id: 2033
label: 0
samples: 0
classCount: Counter()
2020 -

2167 -> 2168

id: 2169
label: 3
samples: 0
classCount: Counter()
2167 -> 2169

id: 2170
label: 3
samples: 0
classCount: Counter()
2167 -> 2170

id: 2171
label: 3
samples: 0
classCount: Counter()
2167 -> 2171

id: 2172
label: 3
samples: 0
classCount: Counter()
2167 -> 2172

id: 2173
label: 3
samples: 0
classCount: Counter()
2167 -> 2173

id: 2174
label: 3
samples: 0
classCount: Counter()
2167 -> 2174

id: 2175
label: 3
samples: 0
classCount: Counter()
2167 -> 2175

id: 2176
label: 3
samples: 0
classCount: Counter()
2167 -> 2176

id: 2177
label: 3
samples: 0
classCount: Counter()
2167 -> 2177

id: 2178
label: 3
samples: 0
classCount: Counter()
2167 -> 2178

id: 2179
label: 7
entropy: 0
samples: 1
classCounts: Counter({7: 1})
value: 11
2167 -> 2179

id: 2180
label: 3
samples: 0
classCount: Counter()
2167 -> 2180

id: 2181
label: 3
samples: 0
classCount: Counter()
2167 -> 2181

id: 2182
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 14
2167 -> 2182

id: 2183
label: 8
en


id: 2330
label: 7
samples: 0
classCount: Counter()
2325 -> 2330

id: 2331
label: 7
samples: 0
classCount: Counter()
2325 -> 2331

id: 2332
label: 7
samples: 0
classCount: Counter()
2325 -> 2332

id: 2333
label: 7
samples: 0
classCount: Counter()
2325 -> 2333

id: 2334
label: 7
samples: 0
classCount: Counter()
2325 -> 2334

id: 2335
label: 8
entropy: 0
samples: 1
classCounts: Counter({8: 1})
value: 9
2325 -> 2335

id: 2337
label: 7
samples: 0
classCount: Counter()
2336 -> 2337

id: 2338
label: 7
samples: 0
classCount: Counter()
2336 -> 2338

id: 2339
label: 7
samples: 0
classCount: Counter()
2336 -> 2339

id: 2340
label: 7
samples: 0
classCount: Counter()
2336 -> 2340

id: 2341
label: 8
entropy: 0
samples: 1
classCounts: Counter({8: 1})
value: 4
2336 -> 2341

id: 2342
label: 7
samples: 0
classCount: Counter()
2336 -> 2342

id: 2343
label: 7
entropy: 0
samples: 1
classCounts: Counter({7: 1})
value: 6
2336 -> 2343

id: 2344
label: 7
samples: 0
classCount: Counter()
2336 -> 2344

id: 2345

2493 -> 2494

id: 2495
label: 7
entropy: 0
samples: 1
classCounts: Counter({7: 1})
value: 1
2493 -> 2495

id: 2496
label: 9
samples: 0
classCount: Counter()
2493 -> 2496

id: 2497
label: 9
samples: 0
classCount: Counter()
2493 -> 2497

id: 2498
label: 9
samples: 0
classCount: Counter()
2493 -> 2498

id: 2499
label: 9
samples: 0
classCount: Counter()
2493 -> 2499

id: 2500
label: 9
samples: 0
classCount: Counter()
2493 -> 2500

id: 2501
label: 9
samples: 0
classCount: Counter()
2493 -> 2501

id: 2502
label: 9
samples: 0
classCount: Counter()
2493 -> 2502

id: 2503
label: 9
samples: 0
classCount: Counter()
2493 -> 2503

id: 2504
label: 9
samples: 0
classCount: Counter()
2493 -> 2504

id: 2505
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 11
2493 -> 2505

id: 2506
label: 9
samples: 0
classCount: Counter()
2493 -> 2506

id: 2507
label: 9
samples: 0
classCount: Counter()
2493 -> 2507

id: 2508
label: 9
samples: 0
classCount: Counter()
2493 -> 2508

id: 2509
label: 9
sam


id: 2637
label: 8
entropy: 0
samples: 1
classCounts: Counter({8: 1})
value: 0
2636 -> 2637

id: 2638
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 1
2636 -> 2638

id: 2639
label: 3
samples: 0
classCount: Counter()
2636 -> 2639

id: 2640
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 3
2636 -> 2640

id: 2641
label: 3
samples: 0
classCount: Counter()
2636 -> 2641

id: 2642
label: 3
samples: 0
classCount: Counter()
2636 -> 2642

id: 2643
label: 3
samples: 0
classCount: Counter()
2636 -> 2643

id: 2644
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 7
2636 -> 2644

id: 2645
label: 3
samples: 0
classCount: Counter()
2636 -> 2645

id: 2646
label: 3
entropy: 0
samples: 3
classCounts: Counter({3: 3})
value: 9
2636 -> 2646

id: 2647
label: 3
entropy: 0
samples: 2
classCounts: Counter({3: 2})
value: 10
2636 -> 2647

id: 2648
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 11
2636 -> 2648

id: 2649
label: 3
samples: 0

2780 -> 2788

id: 2789
label: 8
entropy: 0
samples: 1
classCounts: Counter({8: 1})
value: 8
2780 -> 2789

id: 2790
label: 7
samples: 0
classCount: Counter()
2780 -> 2790

id: 2791
label: 7
samples: 0
classCount: Counter()
2780 -> 2791

id: 2792
label: 7
samples: 0
classCount: Counter()
2780 -> 2792

id: 2793
label: 7
samples: 0
classCount: Counter()
2780 -> 2793

id: 2794
label: 7
samples: 0
classCount: Counter()
2780 -> 2794

id: 2795
label: 7
samples: 0
classCount: Counter()
2780 -> 2795

id: 2796
label: 7
samples: 0
classCount: Counter()
2780 -> 2796

id: 2797
label: 7
samples: 0
classCount: Counter()
2780 -> 2797

id: 2780
attribute: 2
entropy: 1.0
samples: 4
classCounts: Counter({7: 2, 8: 2})
value: 9
2634 -> 2780

id: 2799
label: 8
samples: 0
classCount: Counter()
2798 -> 2799

id: 2800
label: 8
samples: 0
classCount: Counter()
2798 -> 2800

id: 2801
label: 2
entropy: 0
samples: 1
classCounts: Counter({2: 1})
value: 2
2798 -> 2801

id: 2802
label: 8
samples: 0
classCount: Counter


id: 2927
label: 0
samples: 0
classCount: Counter()
2926 -> 2927

id: 2928
label: 0
samples: 0
classCount: Counter()
2926 -> 2928

id: 2929
label: 0
samples: 0
classCount: Counter()
2926 -> 2929

id: 2930
label: 0
samples: 0
classCount: Counter()
2926 -> 2930

id: 2931
label: 0
samples: 0
classCount: Counter()
2926 -> 2931

id: 2932
label: 0
samples: 0
classCount: Counter()
2926 -> 2932

id: 2933
label: 7
entropy: 0
samples: 1
classCounts: Counter({7: 1})
value: 6
2926 -> 2933

id: 2934
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 7
2926 -> 2934

id: 2935
label: 0
samples: 0
classCount: Counter()
2926 -> 2935

id: 2936
label: 0
samples: 0
classCount: Counter()
2926 -> 2936

id: 2937
label: 0
samples: 0
classCount: Counter()
2926 -> 2937

id: 2938
label: 0
samples: 0
classCount: Counter()
2926 -> 2938

id: 2939
label: 0
samples: 0
classCount: Counter()
2926 -> 2939

id: 2940
label: 0
samples: 0
classCount: Counter()
2926 -> 2940

id: 2941
label: 0
entropy: 0
sample

3065 -> 3066

id: 3067
label: 9
samples: 0
classCount: Counter()
3065 -> 3067

id: 3068
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 2
3065 -> 3068

id: 3069
label: 9
samples: 0
classCount: Counter()
3065 -> 3069

id: 3070
label: 9
samples: 0
classCount: Counter()
3065 -> 3070

id: 3071
label: 9
samples: 0
classCount: Counter()
3065 -> 3071

id: 3072
label: 9
entropy: 0
samples: 2
classCounts: Counter({9: 2})
value: 6
3065 -> 3072

id: 3073
label: 9
samples: 0
classCount: Counter()
3065 -> 3073

id: 3074
label: 9
samples: 0
classCount: Counter()
3065 -> 3074

id: 3075
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 9
3065 -> 3075

id: 3076
label: 0
entropy: 0
samples: 1
classCounts: Counter({0: 1})
value: 10
3065 -> 3076

id: 3077
label: 9
samples: 0
classCount: Counter()
3065 -> 3077

id: 3078
label: 9
samples: 0
classCount: Counter()
3065 -> 3078

id: 3079
label: 9
samples: 0
classCount: Counter()
3065 -> 3079

id: 3080
label: 9
entropy: 0
sam

3209 -> 3210

id: 3211
label: 1
entropy: 0
samples: 1
classCounts: Counter({1: 1})
value: 1
3209 -> 3211

id: 3212
label: 9
samples: 0
classCount: Counter()
3209 -> 3212

id: 3213
label: 9
samples: 0
classCount: Counter()
3209 -> 3213

id: 3214
label: 9
samples: 0
classCount: Counter()
3209 -> 3214

id: 3215
label: 9
samples: 0
classCount: Counter()
3209 -> 3215

id: 3216
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 6
3209 -> 3216

id: 3217
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 7
3209 -> 3217

id: 3218
label: 3
entropy: 0
samples: 1
classCounts: Counter({3: 1})
value: 8
3209 -> 3218

id: 3219
label: 9
samples: 0
classCount: Counter()
3209 -> 3219

id: 3220
label: 9
entropy: 0
samples: 1
classCounts: Counter({9: 1})
value: 10
3209 -> 3220

id: 3221
label: 9
samples: 0
classCount: Counter()
3209 -> 3221

id: 3222
label: 9
samples: 0
classCount: Counter()
3209 -> 3222

id: 3223
label: 9
samples: 0
classCount: Counter()
3209 -> 3223

id: 3

In [58]:
pred = id3_clf.predict(X_test, tree)

In [59]:
X_test

array([[0., 0., 0., ..., 2., 0., 0.],
       [0., 0., 5., ..., 3., 0., 0.],
       [0., 0., 2., ..., 3., 0., 0.],
       ...,
       [0., 0., 7., ..., 0., 0., 0.],
       [0., 1., 8., ..., 4., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [60]:
pred

[8,
 0,
 3,
 8,
 2,
 None,
 3,
 None,
 None,
 None,
 5,
 4,
 4,
 4,
 1,
 6,
 6,
 None,
 4,
 3,
 None,
 6,
 5,
 8,
 None,
 9,
 4,
 None,
 6,
 9,
 9,
 0,
 0,
 2,
 None,
 None,
 3,
 4,
 9,
 None,
 3,
 None,
 6,
 3,
 None,
 None,
 7,
 None,
 5,
 0,
 1,
 None,
 9,
 6,
 5,
 None,
 None,
 None,
 None,
 8,
 1,
 None,
 8,
 3,
 3,
 None,
 4,
 2,
 None,
 7,
 9,
 None,
 0,
 3,
 3,
 5,
 None,
 9,
 1,
 3,
 None,
 9,
 None,
 None,
 None,
 2,
 None,
 5,
 None,
 None,
 0,
 0,
 3,
 4,
 9,
 1,
 3,
 7,
 1,
 5,
 0,
 2,
 3,
 4,
 5,
 None,
 9,
 4,
 5,
 7,
 None,
 0,
 5,
 None,
 None,
 2,
 3,
 8,
 8,
 2,
 None,
 0,
 8,
 1,
 0,
 9,
 None,
 1,
 None,
 4,
 1,
 4,
 None,
 2,
 9,
 9,
 7,
 8,
 0,
 7,
 9,
 1,
 None,
 4,
 7,
 2,
 1,
 None,
 None,
 8,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 9,
 6,
 5,
 6,
 None,
 4,
 None,
 None,
 3,
 None,
 7,
 6,
 7,
 5,
 None,
 2,
 None,
 4,
 None,
 5,
 0,
 None,
 None,
 5,
 6,
 1,
 2,
 None,
 1,
 None,
 None,
 7,
 2,
 4,
 4,
 None,
 5,
 3,
 None,
 None,
 None,
 None,
 5,
 7

In [31]:
attributes = {}
possible_vals = ['dark', 'grey', 'light']
for pxl, val in enumerate(X_train.T): 
    attributes[str(pxl)] = possible_vals
    
attributes

{'0': ['dark', 'grey', 'light'],
 '1': ['dark', 'grey', 'light'],
 '2': ['dark', 'grey', 'light'],
 '3': ['dark', 'grey', 'light'],
 '4': ['dark', 'grey', 'light'],
 '5': ['dark', 'grey', 'light'],
 '6': ['dark', 'grey', 'light'],
 '7': ['dark', 'grey', 'light'],
 '8': ['dark', 'grey', 'light'],
 '9': ['dark', 'grey', 'light'],
 '10': ['dark', 'grey', 'light'],
 '11': ['dark', 'grey', 'light'],
 '12': ['dark', 'grey', 'light'],
 '13': ['dark', 'grey', 'light'],
 '14': ['dark', 'grey', 'light'],
 '15': ['dark', 'grey', 'light'],
 '16': ['dark', 'grey', 'light'],
 '17': ['dark', 'grey', 'light'],
 '18': ['dark', 'grey', 'light'],
 '19': ['dark', 'grey', 'light'],
 '20': ['dark', 'grey', 'light'],
 '21': ['dark', 'grey', 'light'],
 '22': ['dark', 'grey', 'light'],
 '23': ['dark', 'grey', 'light'],
 '24': ['dark', 'grey', 'light'],
 '25': ['dark', 'grey', 'light'],
 '26': ['dark', 'grey', 'light'],
 '27': ['dark', 'grey', 'light'],
 '28': ['dark', 'grey', 'light'],
 '29': ['dark', 'grey', 

In [32]:
def num_to_cat(x): 
    if x < 5: 
        return 'dark'
    elif x < 10: 
        return 'gray'
    else: 
        return 'light'

In [46]:
X_train_cat = X_train.copy().astype(str)
for idx, ex in enumerate(X_train): 
    X_train_cat[idx, :] = list(map(num_to_cat, ex))


In [45]:
X_train.dtype

dtype('float64')

In [48]:
id3_clf = ID3DecisionTreeClassifier()

id3_clf.fit(X_train_cat, y_train, attributes, None)


id: 5
label: 7
entropy: 0
samples: 3
classCounts: Counter({7: 3})
value: dark
4 -> 5

id: 6
label: 1
samples: 0
classCount: Counter()
4 -> 6

id: 8
label: 1
entropy: 0
samples: 17
classCounts: Counter({1: 17})
value: dark
7 -> 8

id: 9
label: 1
samples: 0
classCount: Counter()
7 -> 9

id: 10
label: 1
samples: 0
classCount: Counter()
7 -> 10

id: 7
attribute: 41
entropy: 0.7732266742876346
samples: 22
classCounts: Counter({1: 17, 4: 5})
value: light
4 -> 7

id: 4
attribute: 27
entropy: 1.6319667147428167
samples: 34
classCounts: Counter({1: 17, 4: 8, 7: 8, 8: 1})
value: dark
3 -> 4

id: 11
label: 4
samples: 0
classCount: Counter()
3 -> 11

id: 13
label: 8
entropy: 0
samples: 1
classCounts: Counter({8: 1})
value: dark
12 -> 13

id: 14
label: 4
samples: 0
classCount: Counter()
12 -> 14

id: 16
label: 4
samples: 0
classCount: Counter()
15 -> 16

id: 17
label: 4
samples: 0
classCount: Counter()
15 -> 17

id: 18
label: 4
entropy: 0
samples: 22
classCounts: Counter({4: 22})
value: light
15 -


id: 96
label: 2
entropy: 0
samples: 15
classCounts: Counter({2: 15})
value: dark
95 -> 96

id: 97
label: 2
samples: 0
classCount: Counter()
95 -> 97

id: 98
label: 2
entropy: 0
samples: 18
classCounts: Counter({2: 18})
value: light
95 -> 98

id: 95
attribute: 4
entropy: 0.15374218032876188
samples: 45
classCounts: Counter({2: 44, 8: 1})
value: dark
94 -> 95

id: 99
label: 2
samples: 0
classCount: Counter()
94 -> 99

id: 100
label: 7
entropy: 0
samples: 7
classCounts: Counter({7: 7})
value: light
94 -> 100

id: 94
attribute: 34
entropy: 0.7578043140260268
samples: 60
classCounts: Counter({2: 51, 7: 7, 1: 1, 8: 1})
value: light
82 -> 94

id: 82
attribute: 43
entropy: 1.6908810250249464
samples: 126
classCounts: Counter({2: 65, 3: 43, 7: 7, 8: 7, 9: 2, 1: 1, 5: 1})
value: dark
81 -> 82

id: 101
label: 2
samples: 0
classCount: Counter()
81 -> 101

id: 104
label: 5
entropy: 0
samples: 30
classCounts: Counter({5: 30})
value: dark
103 -> 104

id: 105
label: 5
samples: 0
classCount: Counter()

{'id': 0,
 'label': None,
 'attribute': '2',
 'entropy': 3.321026677106508,
 'samples': 1257,
 'classCounts': Counter({6: 124,
          2: 123,
          7: 131,
          3: 133,
          8: 121,
          1: 126,
          0: 127,
          5: 120,
          4: 131,
          9: 121}),
 'nodes': [{'id': 1,
   'label': None,
   'attribute': '61',
   'entropy': 3.049906013401305,
   'samples': 668,
   'classCounts': Counter({7: 71,
            3: 22,
            8: 74,
            1: 100,
            6: 117,
            0: 76,
            4: 129,
            5: 11,
            2: 23,
            9: 45}),
   'nodes': [{'id': 2,
     'label': None,
     'attribute': '10',
     'entropy': 2.5055157881350367,
     'samples': 288,
     'classCounts': Counter({7: 71,
              1: 38,
              0: 27,
              4: 104,
              8: 19,
              5: 8,
              9: 15,
              6: 2,
              3: 3,
              2: 1}),
     'nodes': [{'id': 3,
       'label

In [49]:
plot = id3_clf.make_dot_data()
plot.render('cat_dig')

'cat_dig.pdf'